### ISSUE TITLE
Game Definitions

### ISSUE THREAD

**Issue by Karutoh** [gbowne1/StarshipAscension#6]
`Game.h` Is missing it's definitions and there is and empty `Game` file floating about.

**Comment by gbowne1** [comment]
@Karutoh 

Those are artifacts from the original compile/build. I built some executables when I was trying to test a see if the main and game would compile 

the main program exists in main.cpp and game.h when they need to be renamed. The rest of the files .cpp and .h make up the functionality of the game

**Comment by gbowne1** [comment]
I removed game and the game.h needs to be renamed to main.h and really main.cpp needs to get refactored.  game.h is a artifact of the original program which was game.cpp and game.h
